### ISSUE TITLE
замечания

### ISSUE THREAD

**Issue by demist** [SYury/CDE#1]
+ нет схемы архитектуры

плюсы:
+ хорошая разбивка проекта на отдельные файлы
+ использование cmake
+ за использование констант в коде

**Comment by SYury** [comment]
Добавил.

**Comment by demist** [comment]
Я так и не увидел схему архитектуры, только текстовое описание
Вот тут есть пример: https://www.intuit.ru/studies/higher_education/3406/courses/229/lecture/5956?page=3

**Comment by demist** [comment]
засчитано
